### ISSUE TITLE
salt-2015.8.repo file points to latest directory, not 2015.8 directory

### ISSUE THREAD

**Issue by carlwgeorge** [saltstack/salt-pack#38] opened 2016-02-18 22:15 UTC
The salt-repo packages contain this file.

```
[salt-2015.8]
name=SaltStack 2015.8 Release Channel for RHEL/Centos $releasever
baseurl=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/saltstack-signing-key
```

The version of the package (`2015.8`), the repo id (`salt-2015.8`), and the repo name (`SaltStack 2015.8 Release Channel for RHEL/Centos $releasever`) all indicate that this repo file should be locked to the 2015.8 Release Channel, but the baseurl is pointing to the latest directory.  Please change the baseurl to match the other properties.

```diff
-baseurl=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest
+baseurl=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/2015.8
```

**Comment by dmurphy18** [comment] 2016-02-25 22:21
@carlwgeorge please review the latest documentation on repo.saltstack.com which explains the reasoning behind the use of latest and not 2015.8, that is, pinning.

I would like to close this issue since it is working as designed.

**Comment by carlwgeorge** [comment] 2016-02-25 22:37
Very nice, I like that new layout!  It makes it more clear that you will be updated to the latest release, including major versions.

However, I am still concerned about the repo name in `/etc/yum.repos.d/salt-2015.8.repo` (from the salt-repo package).  Someone viewing that file without looking at the docs could get the wrong impression.  How about this change:

```diff
-name=SaltStack 2015.8 Release Channel for RHEL/Centos $releasever
+name=SaltStack for RHEL/Centos $releasever
```

**Comment by dmurphy18** [comment] 2016-02-29 16:55
@carlwgeorge Wondering if should be salt-latest.repo, and have a spearate salt-2015.8 for the 2015.8 branch, have some 2015.5 rpm's but want to re-check them for the issues you have brought up before making them public.

**Comment by carlwgeorge** [comment] 2016-02-29 17:36
Good call, the filename could also be confusing.  I think the simple name `salt.repo` would be even better.  Then for pinning to a particular release, you can recommend users install the salt-repo package, and modify the baseurl to the version they want to pin to.

**Comment by dmurphy18** [comment] 2016-03-03 00:42
@carlwgeorge The naming is working as designed.  Just updated the install repo rpm's.  It was decided to replace the symbolic link branch name to the full name of the  install repo.rpm.  Also decided to keep the branch name/version for salt-repo-xxxx.rpm since there will be multiples of these for different branches, 2015.8 is just the first branch to have this support.

With this, I would like to close this issue since I believe it has been addressed.

**Comment by dmurphy18** [comment] 2016-05-05 17:21
Need to add a repo rpm for upcoming 2016.3 release, will take opportunity to also create latest repo rpm

**Comment by dmurphy18** [comment] 2016-05-05 21:42
Also updated amazon install rpm too

**Comment by dmurphy18** [comment] 2016-05-05 21:43
Available with next release

**Closed** 2016-06-06 20:29 UTC
Labels: Boron, Packaging, Platform, TEAM Platform
